name: Deploy to irriga.com.tr

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: irriga.com.tr
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          server-dir: /irriga.com.tr/
          exclude: |
            **/.git*
            **/.git*/**
            .cpanel.yml
